[tools]
amazon-ecr-credential-helper = "latest"
ansible = "latest"
argocd = "latest"
atmos = "latest"
aws-cli = "latest"
bat = "latest"
btop = "latest"
bun = "latest"
carapace = "latest"
chezmoi = "latest"
docker-compose = "latest"
eksctl = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gitui = "latest"
go = "latest"
granted = "latest"
helm = "latest"
helm-docs = "latest"
httpie-go = "latest"
jj = "latest"
jq = "latest"
k9s = "latest"
krew = "latest"
kubecm = "latest"
kubecolor = "latest"
kubeconform = "latest"
kubectl = "latest"
kubectx = "latest"
kubeseal = "latest"
kustomize = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@google/gemini-cli" = "latest"
opencode = "latest"
opentofu = "latest"
packer = "latest"
pipx = "latest"
pnpm = "latest"
pre-commit = "latest"
rclone = "latest"
ripgrep = "latest"
starship = "latest"
steampipe = "latest"
terraform = "latest"
terraform-docs = "latest"
terragrunt = "latest"
tflint = "latest"
tlrc = "latest"
uv = "latest"
velero = "latest"
yq = "latest"
zoxide = "latest"
