[tools]
atmos = "latest"
aws-cli = "latest"
bat = "latest"
btop = "latest"
carapace = "latest"
chezmoi = "latest"
docker-compose = "latest"
eksctl = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
helm = "latest"
jj = "latest"
jq = "latest"
k9s = "latest"
krew = "latest"
kubectl = "latest"
kubectx = "latest"
kustomize = "latest"
lazydocker = "latest"
lazygit = "latest"
opentofu = "latest"
packer = "latest"
pipx = "latest"
pnpm = "latest"
pre-commit = "latest"
rclone = "latest"
ripgrep = "latest"
starship = "latest"
terraform-docs = "latest"
terragrunt = "latest"
velero = "latest"
zoxide = "latest"
